// <auto-generated />
using GastCollege3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GastCollege3.Migrations
{
    [DbContext(typeof(E_ventContext))]
    [Migration("20181214143340_updateeee")]
    partial class updateeee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GastCollege3.Models.Aanbieder", b =>
                {
                    b.Property<int>("AanbiederId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("AanbiederId");

                    b.ToTable("Aanbieder");
                });

            modelBuilder.Entity("GastCollege3.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("GastCollege3.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AanbiederId");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<bool>("Full");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("EventId");

                    b.HasIndex("AanbiederId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GastCollege3.Models.Event", b =>
                {
                    b.HasOne("GastCollege3.Models.Aanbieder", "Aanbieder")
                        .WithMany()
                        .HasForeignKey("AanbiederId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GastCollege3.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
